print("dit is mijn HelloYou text based applicatie")
print("ik ben Menno\n")
jouwNaam = input("hoe heet jij???? ")
print (jouwNaam + " welkom op mijn site ")


 
print("Goedemorgen/ Middag, mag ik u een paar vragen stellen over hoe het met u gaat ?")
print("         ")
print("wilt u de vragenlijst invullen")
keuze = input("j of n ")
if keuze == "j":
     print("Fijn dat ik u een paar vragen mag stellen. Hoe gaat het met u?")
     print("         ")
soort = input("goed / slecht/ gewoon ")
if soort == "goed": print("fijn dat het goed gaat")
if soort == "slecht": print("vervelend dat het niet zo goed gaat. Is er iets wat ik voor u kan betekenen?")
if soort == "gewoon": print("Fijn")
print("         ")
print("Vind u het goed als ik hier iets dieper op in ga?")
print("                                 ")
keuze1 = input("j of n ")
print("wilt u het gesprek liever beëindigen")
print("         ")
keuze1a = input("j of n ")
if keuze1a == "n": print ("bedankt voor uw medewerking tot zo ver.")
if keuze1a == "j": print ("fijn dat u nog een paar vragen wilt beantwoorden.")
print("Heeft deze COVID periode invloed op uw gemoedstoestand?")
print("         ")
keuze2 = input("j of n ")
print("         ")
if keuze2 == "j": print ("in welk opzicht; somber/ alleen/ bang ")
if keuze2 == "n": print ("Fijn dat dit geen invloed heeft, maar voelt u zich wel eens")
keuze2a = input("somber, alleen, bang ")
print("         ")
if keuze2a == "somber": print ("wat vervelend voor u dat de sombere stemming overheerst, kan ik u hierbij helpen")
if keuze2a == "alleen":print ("vervelend dat u zich alleen voelt. Kan een vrijwilligster iets voor u betekenen ?")
if keuze2a == "bang": print ("bent u bang voor eventuele gezondheidsgevolgen of voor de gevolgen voor de economie")
keuze3 = input("j of n ")
print("         ")
if keuze3 == "n": print ("bedankt voor uw medewerking, dit waren me vragen.")
if keuze3 == "j": print ("Kan een vrijwilligster iets voor u betekenen ?")
print("                            ")
keuze4 = input("j of n ")
if keuze4 == "n": print ("mocht ik toch van dienst kunnen zijn hoor ik het graag. Ik wens u een prettige dag verder")
if keuze4 == "j": print ("denkt u dat dit voor eventuele gezondheidsgevolgen heeft of voor de gevolgen voor de economie")
else: print ("geen probleem ik wens u een prettige dag verder")
print("                   ")
if keuze5 == "j": print("gezondheid, economie of gewoon ")
print("         ")
if keuze5 == "gezondheid": print ("dat raad ik u aan even contact op te nemen met uw huisarts")
if keuze5 == "economie": print ("ik snap het en hoop ook dat de gevolgen voor de economie beperkt blijven.")
if keuze5 == "gewoon": print ("fijn dat het naar wens gaat")

